name: julienangevin
favicon: null
layout_spectrum: 0.963166
typography_spectrum: 0.9426523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7393b9'
    - '#69773a'
    - '#1d2d08'
    - '#dbd5bc'
    - '#c3a17b'
  brandStrength: 0.5
  lightness: 0.4462366
  saturation: 0.4770748
  rhythmicContrast: 0.811828
purpose: []
