layout_spectrum: 0.963166
color:
  saturation: 0.4770748
  lightness: 0.4462366
  brandStrength: 0.6935484
  rhythmicContrast: 0.811828
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.9426523
name: julienangevin
